QuangNDDev/Fashion_Rental_Fe

src/App.js
src/components/Card/CardDetail.jsx
src/components/Mutil-Image/index.jsx
src/components/Staff-Grid/index.jsx
src/components/admin-table/CustomerTable.jsx
src/index.js
src/pages/admin-login/admin-login.jsx
src/pages/admin/Admin.jsx
src/pages/staff/Staff.jsx

fix Staff UI

---

src/App.js

fix conflict

---

src/components/Card/CardDetail.jsx

update staff UI

---

src/App.js
src/components/protect-page/Protect-Page-Admin.jsx
src/components/protect-page/Protect-Pages-Staff.jsx
src/pages/admin-login/admin-login.jsx

login staff and protect route staff

login staff and protect route staff

---

src/pages/staff/Staff.jsx

handleLogout

---

src/components/Card/CardDetail.jsx
src/components/Mutil-Image/index.jsx

get information to modal

---

src/App.js
src/components/RegisterForm/RegisterForm.css
src/components/RegisterForm/index.jsx

RegisterForm UI

---

src/components/RegisterForm/RegisterForm.css
src/components/RegisterForm/index.jsx

RegisterForm

---

src/components/RegisterForm/RegisterForm.css
src/components/RegisterForm/index.jsx

fixbug display form cus and po

fixbug display form cus and po

---

src/components/RegisterForm/index.jsx
src/pages/admin-login/admin-login.jsx
src/pages/staff/Staff.jsx

call api header staff

---

src/components/RegisterForm/index.jsx
src/components/admin-table/CustomerTable.jsx
src/components/admin-table/ProductOwnerTable.jsx
src/components/admin-table/StaffTable.jsx
src/components/create-product/create-product.jsx
src/components/information-staff/index.jsx
src/pages/admin-login/admin-login.jsx

fix notification all role style drawer

fix notification all role style drawer

---

src/components/create-product/create-product.css
src/components/create-product/create-product.jsx

form create product test

---

src/components/create-product/create-product.css
src/components/create-product/create-product.jsx

create product form and regex: only value number

create product form and regex: only value number

---

src/components/infomation-productonwer/information-productowner.jsx
src/components/information-staff/index.jsx
src/components/information-staff/style.css

profilePO test

---

src/components/Card/CardDetail.jsx
src/components/Staff-Grid/index.jsx
src/components/admin-table/CustomerTable.jsx
src/components/admin-table/ProductOwnerTable.jsx
src/components/admin-table/StaffTable.jsx
src/components/create-product/create-product.jsx
src/components/product-card/product-card.jsx

notification create product, regex number and check null input

notification create product, regex number and check null input

---

src/components/create-product/create-product.jsx
src/components/product-card/product-card.jsx

add condition product

---

src/components/Staff-Grid/accept.jsx
src/components/Staff-Grid/index.jsx
src/components/create-product/create-product.jsx
src/components/render/RenderTag.jsx

display image

---

package-lock.json
src/components/Mutil-Image/index.jsx
src/components/Staff-Grid/accept.jsx
src/components/Staff-Grid/index.jsx

format date and preview datail image

format date and preview datail image

---

src/components/create-product/create-product.css
src/components/create-product/create-product.jsx
src/components/product-card/product-card.jsx

form watch

---

src/components/create-product/create-product.css
src/components/create-product/create-product.jsx

form earring, shoe and css

---

src/components/create-product/create-product.css
src/components/create-product/create-product.jsx

Hat form and css form

---

src/components/balance-productowner/balance-productowner.jsx
src/components/balance-productowner/transaction-history-table.jsx
src/components/revenue-product-owner/revenue.jsx
src/components/voucher-form/index.jsx

update balane layout

---

src/components/voucher-form/index.jsx

formate date to string

---

src/components/Staff-Grid/accept.jsx
src/components/Staff-Grid/index.jsx
src/components/Staff-Grid/reject.jsx
src/components/product-card/product-card.jsx
src/components/render/RenderTag.jsx
src/components/voucher-form/index.jsx

fix approve product and reject product

fix approve product and reject product

---

src/components/voucher-form/index.jsx

format date to string

---

package-lock.json
package.json
src/components/balance-productowner/balance-productowner.jsx
src/components/product-owner-table/OrderRent.jsx
src/components/revenue-product-owner/revenue.jsx
src/components/voucher-form/index.jsx
src/pages/product-owner/product-owner.jsx
src/pages/staff/Staff.jsx

add table fix layout

---

src/components/Staff-Grid/accept.jsx
src/components/Staff-Grid/index.jsx
src/components/Staff-Grid/reject.jsx
src/components/balance-productowner/balance-productowner.jsx
src/components/order-buy/index.jsx
src/components/product-owner-table/OrderTable.jsx
src/components/revenue-product-owner/revenue.jsx
src/pages/product-owner/product-owner.jsx
src/pages/staff/Staff.jsx

call api get all order buy

---

src/components/order-delivery/order-delivery-table.jsx

regex shipping

---

src/components/balance-productowner/balance-productowner.jsx
src/components/order-delivery/order-delivery-table.jsx

regex nap tien

---

src/components/Staff-Grid/accept.jsx
src/components/Staff-Grid/index.jsx
src/components/Staff-Grid/reject.jsx
src/components/admin-table/CustomerTable.jsx
src/components/create-product/create-product.jsx
src/components/product-owner-table/ReturnOrderSale.jsx
src/firebase/firebase.js
src/pages/admin-login/admin-login.jsx
src/pages/product-owner/product-owner.jsx
src/pages/staff/Staff.jsx

login google, responsive table

login google, responsive table

---

src/components/order-buy/index.jsx
src/components/order-rent/index.jsx
src/components/product-card/product-card.jsx
src/components/product-owner-table/CancelOrderRent.jsx
src/components/product-owner-table/CancelOrderTable.jsx
src/components/product-owner-table/OrderRent.jsx
src/components/product-owner-table/OrderTable.jsx
src/components/product-owner-table/Product-Order.jsx
src/components/product-owner-table/ReturnOrderSale.jsx
src/pages/staff/Staff.jsx

fix login google and get add orders rent of staff

fix login google and get add orders rent of staff

---

src/components/RegisterForm/index.jsx
src/components/create-product/create-product.jsx
src/components/order-buy/cancel-buy-staff.jsx
src/components/order-rent/cancel-rent-staff.jsx
src/components/product-card/product-card.jsx
src/components/voucher-form/index.jsx
src/components/voucher-form/voucher-table.jsx
src/pages/admin/Admin.jsx
src/pages/product-owner/product-owner.jsx
src/pages/staff/Staff.jsx

update admin layout, all orderRent and orderBuy Staff hover card in productCard

update admin layout, all orderRent and orderBuy Staff hover card in productCard

---

src/components/admin-table/CustomerTable.jsx
src/components/admin-table/ProductOwnerTable.jsx
src/components/admin-table/StaffTable.jsx
src/firebase/firebase.js

fix firebase and check sapce admin, PO

fix firebase and check sapce admin, PO

---

src/components/Staff-Grid/accept.jsx
src/components/Staff-Grid/index.jsx
src/components/Staff-Grid/reject.jsx
src/components/admin-table/CustomerTable.jsx
src/components/admin-table/ProductOwnerTable.jsx
src/components/admin-table/StaffTable.jsx
src/components/balance-productowner/transaction-history-table.jsx
src/components/order-delivery/order-rent-delivery.jsx
src/components/order-rent/cancel-rent-staff.jsx
src/components/product-owner-table/OrderRent.jsx
src/components/product-owner-table/OrderTable.jsx
src/components/product-owner-table/Product-Order.jsx
src/components/revenue-product-owner/revenue-table.jsx
src/components/voucher-form/index.jsx
src/components/voucher-form/voucher-table.jsx

add quality in voucher, delete width in table, add rent price to drawer staff

add quality in voucher, delete width in table, add rent price to drawer staff

---

src/components/Staff-Grid/request.jsx
src/components/product-owner-table/CompletedOrderSale.jsx

update layout manage request staff

update layout manage request staff

---

src/components/Staff-Grid/accept.jsx
src/components/Staff-Grid/index.jsx
src/components/Staff-Grid/reject.jsx
src/components/create-product/create-product.jsx
src/components/order-delivery/order-rent-delivery.jsx
src/components/product-card/product-card.jsx
src/pages/product-owner/product-owner.jsx
src/pages/staff/Staff.jsx

fix rating
